services:
    php:
        build:
            context: ./.docker/php/
            args:
                USER_ID: '${USER_ID:-1000}'
                GROUP_ID: '${GROUP_ID:-1000}'
        volumes:
            - ./:/app
        command: /scripts/keep-alive.sh
